Incorporate master slave setup and limit feed reset
heinoskov/huawei-solar-battery-optimizations pull request #15
Opened 2024-10-03 08:21 UTC by JensenNick

2024-10-03 18:20 UTC, heinoskov requested changes

2024-10-03 18:20 UTC, heinoskov commented on huawei_solar_battery_optimization.yaml
> +          device_id: "{{ states('input_text.hsbo_device_id_inverter_2') }}"
Se ovenstående vedr. condition check vedr. inverter2

2024-10-03 18:20 UTC, heinoskov commented on huawei_solar_battery_optimization.yaml
> +      - action: huawei_solar.reset_maximum_feed_grid_power #Foretrækker denne, da den resetter anlægget til default export.
se 2 kommentarer ovenover

2024-10-03 18:20 UTC, heinoskov commented on huawei_solar_battery_optimization.yaml
> +                          {{ states(inverter_entity) != "Limited to 0.0%" }} #Forslag: Blot kald det for "Limit Export"
parameteren der sættes er "Limited to 0.0%" - så kan ikke ændre denne tekst.... men hvis vi alligevel ændrer væk fra % og over på W så skal denne alligevel ændres.

2024-10-03 18:20 UTC, heinoskov commented on huawei_solar_battery_optimization.yaml
> +                          {{ states(inverter_entity) != "Limited to 100.0%" }} #Forslag: Blot kald det for "Reset Export"
parameteren der sættes er "Limited to 100.0%" - så kan ikke ændre denne tekst.... men hvis vi alligevel ændrer væk fra % og over på W så skal denne alligevel ændres.

2024-10-03 18:20 UTC, heinoskov commented on huawei_solar_battery_optimization_input.yaml
> +# Eller tænker i at man gør det et andet sted?
gøres i enten developer tools - state eller i lovelace dashboard

2024-10-06 09:36 UTC, JensenNick commented on huawei_solar_battery_optimization.yaml
> +
Det der er afgørende for op-/aflade-effekt er antallet af batteripakker. Med LUNA2000 S0 har man hhv. en op-/aflade-effekt på 2500W med en 5kWh batteripakke (1 modul) og 5000W med en 10 eller 15kWh batteripakke (2 eller 3 moduler). Med LUNA2000 S1 (den nye model med 7kWh moduler) har man en op-/aflade-effekt på 3500W med en 7kWh batteripakke (1 modul), 7000W med en 14kWh batteripakke (2 moduler) og 10500W med en 21kWh batteripakke (3 moduler). Sat i serie fordobles lade-effekten tilsvarende.

2024-10-06 09:46 UTC, JensenNick commented on huawei_solar_battery_optimization.yaml
> +      - action: huawei_solar.set_maximum_feed_grid_power #Foretrækker denne da man med denne sætter et antal W der må sendes til grid i stedet for en % sats af ???
Jeg mener det er mere rigtigt at angive hvor meget man vil sende til grid i W frem for %. Jeg er i tvivl om hvad der menes med % - fordi % af hvad?

Det er ikke (økpnomisk) ønskeligt at forhindre feed to grid helt, fordi det medfører at du kommer til at importere (en smule). Strørm er en sjov størrelse. Det står hele tiden og "skvulper" frem og tilbage. Hvis du sætter feed til 0% eller anvender funktionen zero export, så vil du opleve at du i praksis køber små mængder strøm. Typisk er prisen på eksport så lav at det bedre kan betale sig at sende lidt strøm til nettet frem for at købe. Derfor er det at foretrække at anvende limit export to grid og sætte denne. Jeg har sat min 3-fasede inverter til 200W og min 1-fasede til 100W. Det fungerer rigtigt fint. Jeg køber sjældent noget med disse indstillinger - og salget er så beskedent at det ikke har noget at sige.

Der kan selvfølgeligt være ekstreme situationer, som den vi oplevede sidste år med en salgsomkostning på 7 kr, hvor ovenstående ikke ergældende - dette bør man naturligtvis sætte en grænse for (eksempelvis som en trigger at når salgspris > købspris).

2024-10-06 09:47 UTC, JensenNick commented on huawei_solar_battery_optimization.yaml
> +          device_id: "{{ states('input_text.hsbo_device_id_inverter_2') }}"
Jeg ved ikke om det trigger en fejl. Jeg kommer til kort her ift. HA og yaml.

2024-10-06 13:24 UTC, heinoskov commented on huawei_solar_battery_optimization.yaml
> +
Det er en god pointe og det skal vi jo tage højde for (hvilket vi ikke gør lige pt.)

2024-10-06 13:26 UTC, heinoskov commented on huawei_solar_battery_optimization.yaml
> +          device_id: "{{ states('input_text.hsbo_device_id_inverter_2') }}"
Hvordan fungere det med master / slave...  - styrer man bare masteren og den sørger for at slaven følger samme indstillinger? Kan du forsøge at lave en definition omkring hvordan det virker?

2024-10-06 13:27 UTC, heinoskov commented
@JensenNick har lige svaret på et par af dine kommentarer :-)

2024-10-11 05:46 UTC, closed without merging